name: Do stuff on merge

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      if: github.event.pull_request.merged
    - run: |
        contents=$(cat a)
        git tag "${contents}"
        git push "https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" refs/tags/"${contents}"
