name: Do stuff on merge

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: |
        echo Add other actions to build,
        echo test, and deploy your project.
