name: Do stuff on merge

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      if: github.event.pull_request.merged
    - run: |
        git tag hoho
        git push --tags
