name: Do stuff on merge

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      if: github.event.pull_request.merged
    - run: git tag hoho
    - uses: ad-m/github-push-action@v.0.4.0
      with:
        branch: hoho
        github_token: ${{ secrets.GITHUB_TOKEN }}
