name: Tag on push to master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Push tag
      run: |
        if git diff --exit-code HEAD^ -- a; then
          echo "No change in file a."
        else
          contents=$(cat a)
          git tag "${contents}"
          git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" refs/tags/"${contents}"
        fi
